src/landinghub/urls.py
from django.contrib import admin
#from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from webpages.views import home_view, landinghub_view

#from landings.views import landing_list_view, landing_detail_view, landing_create_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', home_view, name='home'),
    path('landinghub/', landinghub_view, name='landinghub_view'),
    path('landings/', include('landings.urls')),
    path('virtual-rooms/', include('virtualrooms.urls')),
    path('newsletter/', include('signups.urls')),
    path('moreinfo/', include('moreinfos.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/landings/urls.py
from django.contrib import admin
from django.urls import path
from landings.views import (
	# landing_list_view, 
	# landing_detail_view, 
	# landing_create_view,
	landing_page,
	#LandingPageDetailView,
	LandingPageListView,
	LandingPageCreateView,
	LandingPageUpdateView,
	LandingPageDeleteView,
)

app_name = 'landings'
urlpatterns = [
    #path('', landing_list_view, name='landing-list'),
    path('all/', LandingPageListView.as_view() , name='landing-list'),
    #path('create/', landing_create_view, name='landing-create'),
    path('create/', LandingPageCreateView.as_view(), name='landing-create'),
    path('<int:pk>/edit/', LandingPageUpdateView.as_view(), name='landing-update'),
    path('<int:pk>/delete/', LandingPageDeleteView.as_view(), name='landing-delete'),
    path('<slug:slug>/', landing_page, name='landing-detail'),
    #path('<slug:slug>/', LandingPageDetailView.as_view(), name='landing-detail'),
]

src/signups/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
	NewsletterSignupView,
	NewsletterSignupListView,
)

app_name = 'signups'
urlpatterns = [
    path('<int:pk>/signup/', NewsletterSignupView.as_view(), name='newsletter-signup'),
    path('<int:pk>/subscriptions/', NewsletterSignupListView.as_view(), name='newsletter-subscriptions'),
  
]

src/signups/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

#Registro de clientes al newsletter
class SignUp(models.Model):
    email = models.EmailField()
    name = models.CharField(_('name'), max_length=240, blank=True, null=True)
    phone_number = models.CharField(_('phone number (cell)'), max_length=60, null=True, blank=True)
    obj_interest_id = models.IntegerField(_('product ID.'), blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
    	if self.active:
    		return "%s %s" %(self.email, 'is subscribed')
    	else:
    		return "%s %s" %(self.email, 'is unsubscribed')

src/signups/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import SignUp

class SignUpForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super(SignUpForm, self).__init__(*args, **kwargs)
	    #Aquí puedo hacer modificaciones al modelo y la presentación
	    #del formulario
		self.fields['email'].widget.attrs.update({'required': 'required'})
		#self.fields['email'].label = _("Correo electrónico:")
		self.fields['name'].label = _("Name:")

	class Meta:
		model = SignUp
		fields = ['name','email', 'obj_interest_id']
		widgets = {
			'obj_interest_id': forms.HiddenInput(),
			'email': forms.TextInput(attrs={'placeholder': 'abc@email.com'}),
		}

src/signups/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.html import format_html
from django.utils.translation import ugettext_lazy as _
from mailer import send_mail, send_html_mail
from django import forms
from django.views.generic import (
	CreateView,
	ListView,
)

#from .utils import get_mailchimp_api
from .forms import SignUpForm
from .models import SignUp
from landings.models import LandingPage

#Project Vars
project_logo = settings.PROJECT_LOGO
project_name = settings.PROJECT_NAME
project_domain = settings.PROJECT_DOMAIN
project_product_desc = settings.PRODUCT_DESCRIPTION

class AjaxTemplateMixin(object):

     def dispatch(self, request, *args, **kwargs):
        if not hasattr(self, 'ajax_template_name'):
            split = self.template_name.split('.html')
            split[-1] = '_inner'
            split.append('.html')
            self.ajax_template_name = ''.join(split)
        if request.is_ajax():
            self.template_name = self.ajax_template_name
        return super(AjaxTemplateMixin, self).dispatch(request, *args, **kwargs)

class NewsletterSignupView(SuccessMessageMixin, AjaxTemplateMixin, CreateView):
	#model = SignUp
	template_name = 'signups/newsletter_popup_form.html'
	form_class = SignUpForm
	success_url = reverse_lazy('home')
	#success_message = _("¡Perfecto! Nos comunicamos contigo para ver en cúal curso te interesa aplicar tu beca.")

	def dispatch(self, request, *args, **kwargs):
	    landing = LandingPage.objects.get(id=kwargs['pk'])
	    return super(NewsletterSignupView, self).dispatch(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
	    # Call the base implementation first to get a context
	    context = super(NewsletterSignupView, self).get_context_data(**kwargs)
	    # Add in a QuerySet
	    #landingpage for acitivity get discount
	    landing = LandingPage.objects.get(id=self.kwargs['pk']) 
	    context['landing_id'] = self.kwargs['pk']
	    context['main_header'] = _('Receive exclusive discounts and information about new products and promotions!')
	    context['sub_header'] = _('By subscribing to the Newsletter we will notify you of special discounts and new product launches')
	    form_btn_text = _("I'm interested!")
	    context['btn_submit'] = form_btn_text
	    return context

	def form_valid(self, form):
		instance = form.save(commit=False)
		#email = instance.email
		#fname = instance.first_name
		email = form.cleaned_data.get("email")
		fname = form.cleaned_data['name']
		if not form.cleaned_data['name']:
			fname = '-'
		instance.obj_interest_id = self.kwargs['pk']
		#phone = instance.phone_number
		instance.save()
		# list_id = 'f5a3186ffc'
		# m = get_mailchimp_api()
		# try:
		#     fields={'FNAME':fname}
		#     m.lists.members.create(list_id, { 'email_address': email, 'status': 'subscribed', 'merge_fields':fields, })
		#     try:
		#         SignUp.objects.get_or_create(email=email, first_name=fname)
		#     except Exception as e:
		#         print(e)
		# except Exception as e:
		#     print(e)
		try:
			remitente = settings.EMAIL_PLATFORM
			destinatario = [settings.EMAIL_MAIN]
			sbj = "%s -%s" %(_('New Newsletter subscriber'), project_name)
			url = "https://%s/newsletter/%s/subscriptions/" %(project_domain, str(instance.obj_interest_id))
			msg = "%s" %(_('New subscriber!'))
			msg_bye = "%s -%s" %(_('Best regards'), project_name)
			send_html_mail(sbj, msg, '<table width="100%" border="0" cellspacing="0" cellpadding="0"><tr><td width="10%" align="center" valign="top" style="font-family:Open Sans, Helvetica Neue, Helvetica, Helvetica, Arial, sans-serif; font-size:2px; font-weight:300; color:#294661;">.</td><td width="80%" align="center" valign="top" bgcolor="#f7f7f7"><h2> '+ msg +' </h2><h2 class="text-center">' + fname + '</h2>(<a href=' + url + '>' + url +'</a>)<h3 class="text-center" style="color:#007D8C;"><a href="mailto:'+ email + '">' + email + '</a></strong></h3><p>'+ msg_bye +'<br><br></p></td><td width="10%" align="center" valign="top" style="font-family:Arial, Helvetica, sans-serif; font-size:2px; color:#ffffff;">.</td></tr></table>', remitente, destinatario, fail_silently=False)
		except Exception as e:
			print('error here 1')
			print(e)
			pass
		try:
			remitente = settings.EMAIL_MAIN
			destinatario = [email]
			sbj = "%s -%s" %(_('Thank you for subscribing'), project_name)
			msg = "%s %s" %(fname, _('Welcome to our Newsletter!'))
			msg2 = "%s" %(_('We will keep you updated with the latest news and updates, and you will receive the exclusive discounts we have for you.'))
			#send_html_mail(sbj, msg, '<table width="100%" border="0" cellspacing="0" cellpadding="0"><tr><td width="10%" align="center" valign="top" style="font-family:Open Sans, Helvetica Neue, Helvetica, Helvetica, Arial, sans-serif; font-size:2px; font-weight:300; color:#294661;">.</td><td width="80%" align="center" valign="top" bgcolor="#f7f7f7"><h2>'+ msg +'</h2><h3>'+ msg2 +'</h3><br><p>' + msg_bye + '</p></td><td width="10%" align="center" valign="top" style="font-family:Arial, Helvetica, sans-serif; font-size:2px; color:#ffffff;">.</td></tr></table>', remitente, destinatario, fail_silently=False)
			#send_html_mail(sbj, msg, "' '",remitente, destinatario, fail_silently=False )
		except Exception as e:
			print('error here 2')
			print(e)
			pass
		return HttpResponseRedirect(self.success_url)
		#return super(NewsletterSignupView, self).form_valid(form)

class NewsletterSignupListView(LoginRequiredMixin, ListView):
	
	def get_context_data(self, **kwargs):
		context = super(NewsletterSignupListView, self).get_context_data(**kwargs)
		context['project_logo'] = project_logo
		context['project_name'] = project_name
		context['title'] = _('Newsletter Subscriptions')
		activity = get_object_or_404(LandingPage, id=self.kwargs['pk'])
		context['landing'] = activity
		return context

	def get_queryset(self):
		activity = get_object_or_404(LandingPage, id=self.kwargs['pk'])
		queryset = SignUp.objects.filter(obj_interest_id=activity.id).order_by('-timestamp')
		return queryset

src/signups/templates/signups/newsletter_popup_form.html
{% load i18n %}
{% block head_title %} {{title}} {% endblock %}
{% block style %} {% endblock %}
{% block content %}
{% include 'signups/newsletter_popup_form_inner.html' %}
{% endblock %}

src/signups/templates/signups/newsletter_popup_form_inner.html
{% load crispy_forms_tags %}
{% load i18n %}
{% load tz %}
<div class="row">
	<div class="col-sm-12 col-xs-12">
		<div class="panel">
			<br>
			<a data-dismiss="modal" aria-hidden="true" class="btn btn-default btn-xs" style="float:right;">{% trans 'x' %}</a>
		  	<div class="panel-body">
					<div style="text-align:center">
						<h4><b>{{main_header}}</h4></b>
						<br>
						<small>{{sub_header}}</small>
					</div>
					<br>
          {% if form %}
		{{ form.media }}
			<form class="form-horizontal" method='POST' action="{% url 'signups:newsletter-signup' landing_id %}">{% csrf_token %}
					{{ form | crispy }}
					<br>
					<input type='submit' value= "{{btn_submit}} &raquo;" class='btn btn-block btn-success btn-lg' ></input>
			</form>
		{% endif %}
        </div>
    </div>
	</div>
</div>
{% block js %}
{% endblock %}

src/signups/templates/signups/signup_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block head_title %} {{title}} {% endblock %}
{% block content %}
{% include "navbar.html" %}
<br>
<main role="main">
	<div class="jumbotron">
			<div class="text-center">
	        	<h4><b>{% trans 'Newsletter subscriptions in' %}</b> <br>{{landing}}</h4> 
	        </div>
	  		<br>
	        <div>
	        <div class="table-responsive">
	        {% if object_list %}
			<table class="table table-bordered table-sm text-center">
			  <thead>
			    <tr>
			      <th scope="col">{% trans 'E-mail' %}</th>
			      <th scope="col">{% trans 'Name' %} </th>
			      <th scope="col">{% trans 'Phone Number' %}</th>
			      <th scope="col">{% trans 'When?' %}</th>
			    </tr>
			  </thead>
			  <tbody>
			  	{% for object in object_list %}
			    <tr>
			      <td>{{object.email}}</td>
			      <td>{{object.name|default_if_none:"--"}}</td>
			      <td>{{object.phone_number|default_if_none:"--"}}</td>
			      <td>{{object.timestamp}}</td>
			    </tr>
			    {% endfor %}
			  </tbody>
			</table>			
			{% else %}
			<h6 class="text-center"><b>{% trans 'Sorry, no subscribers via this Landing Page.' %}</b></h6>
			{% endif %}
		 </div>
		 </div>
		 <a href="{% url 'landings:landing-list' %}"  style="float:left;" class="btn btn-primary btn-sm">&laquo; {% trans 'My Landing Pages'%}</a>
	</div>
	
{% include 'footer.html' %} 
</main>
{% endblock %}