src/landinghub/urls.py
from django.contrib import admin
#from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from webpages.views import home_view, landinghub_view

#from landings.views import landing_list_view, landing_detail_view, landing_create_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', home_view, name='home'),
    path('landinghub/', landinghub_view, name='landinghub_view'),
    path('landings/', include('landings.urls')),
    path('virtual-rooms/', include('virtualrooms.urls')),
    path('newsletter/', include('signups.urls')),
    path('moreinfo/', include('moreinfos.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/landings/urls.py
from django.contrib import admin
from django.urls import path
from landings.views import (
	# landing_list_view, 
	# landing_detail_view, 
	# landing_create_view,
	landing_page,
	#LandingPageDetailView,
	LandingPageListView,
	LandingPageCreateView,
	LandingPageUpdateView,
	LandingPageDeleteView,
)

app_name = 'landings'
urlpatterns = [
    #path('', landing_list_view, name='landing-list'),
    path('all/', LandingPageListView.as_view() , name='landing-list'),
    #path('create/', landing_create_view, name='landing-create'),
    path('create/', LandingPageCreateView.as_view(), name='landing-create'),
    path('<int:pk>/edit/', LandingPageUpdateView.as_view(), name='landing-update'),
    path('<int:pk>/delete/', LandingPageDeleteView.as_view(), name='landing-delete'),
    path('<slug:slug>/', landing_page, name='landing-detail'),
    #path('<slug:slug>/', LandingPageDetailView.as_view(), name='landing-detail'),
]

src/signups/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
	NewsletterSignupView,
	NewsletterSignupListView,
)

app_name = 'signups'
urlpatterns = [
    path('<int:pk>/signup/', NewsletterSignupView.as_view(), name='newsletter-signup'),
    path('<int:pk>/subscriptions/', NewsletterSignupListView.as_view(), name='newsletter-subscriptions'),
  
]

src/virtualrooms/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
	virtualroom_page,
    VirtualRoomAttendeeSignupView,
    VirtualRoomAttendeeListView,
	#VirtualRoomPageDetailView,
	VirtualRoomPageListView,
	VirtualRoomPageCreateView,
	VirtualRoomPageUpdateView,
	VirtualRoomMaterialUploadView,
	VirtualRoomPageDeleteView,
)

from .ajax import (
    delete_session_material_post,
    inactive_session_material_post,
    active_session_material_post,
)

app_name = 'virtualrooms'
urlpatterns = [
    #path('', landing_list_view, name='landing-list'),
    path('all/', VirtualRoomPageListView.as_view() , name='virtualroom-list'),
    #path('create/', landing_create_view, name='landing-create'),
    path('create/', VirtualRoomPageCreateView.as_view(), name='virtualroom-create'),
    path('<int:pk>/edit/', VirtualRoomPageUpdateView.as_view(), name='virtualroom-update'),
    path('<int:pk>/upload/material/', VirtualRoomMaterialUploadView.as_view(), name='virtualroom-materials'),
    path('<int:pk>/delete/', VirtualRoomPageDeleteView.as_view(), name='virtualroom-delete'),
    path('<slug:slug>/', virtualroom_page, name='virtualroom-detail'),
    path('<int:pk>/attendee/signup/', VirtualRoomAttendeeSignupView.as_view(), name='attendee-signup'),
    path('<int:pk>/attendees/', VirtualRoomAttendeeListView.as_view(), name='attendees-list'),
    path('active/material/', active_session_material_post, name='ajax-active-session-material'),
    path('inactive/material/', inactive_session_material_post, name='ajax-inactive-session-material'),
    path('delete/material/', delete_session_material_post, name='ajax-delete-session-material'),
]

src/landings/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.utils.text import slugify
from django.contrib.auth.models import User
from djmoney.models.fields import MoneyField

from landinghub.utils import unique_slug_generator

User = settings.AUTH_USER_MODEL

def landingfile_upload_to(instance, filename):
	ext = filename.split('.')[-1]
	filename = '{}.{}'.format(instance.slug, ext)
	return 'landinghub/files/%s/landings/%s' % (instance.owner, filename)

NEWSLETTER_CHOICES = (
        ('NO', 'No'),
		('YNL', _('Yes. Newsletter')),
		# ('YNLD', _('Sí. Newsletter + Cupón Descuento')),
	)

class LandingPage(models.Model):
	owner = models.ForeignKey(User, verbose_name=_('user'), on_delete=models.CASCADE) # class_instance.model_set.all() #Check CFE Django User model unleashed
	title = models.CharField(_('landing page header'), max_length=100, help_text=_('A catchy title or name for the page.'))
	title_form = models.CharField(_('form title'), max_length=100, help_text=_('Title for the contact form.'), default='DO YOU WANT MORE INFORMATION?')
	slug = models.SlugField(blank=True, null=False, unique=True, max_length=200)
	clock = models.DateTimeField(_('date/time countdown'), help_text=_('Use this field only if you want a countdown to be displayed.'), blank=True, null=True)
	price = MoneyField(_('price to show'), max_digits=19, decimal_places=4, default_currency='USD', blank=True, null=True, help_text=_('Use this field only if you want a price to be displayed.'))
	file = models.FileField(_('file'), upload_to=landingfile_upload_to, editable=True, help_text=_("Upload main file to show in the Landing Page (pdf, ppt, image, video, mp3, etc.)."))
	file_type = models.CharField(max_length=25, null=True)
	newsletter_popup = models.CharField(_('Newsletter subscription pop-up window?'), max_length=4,
	                                  choices=NEWSLETTER_CHOICES,
	                                  default='NO',
									  help_text=_('A pop-up window for visitors to subscribe to your mailing list.'))
	#newsletter_discount = models.IntegerField(_('offer discount coupon of'), default=10, help_text=_('Enter the whole number corresponding to the discount percentage (not including the "%" symbol).'))
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)

	def __str__(self):
		return 'Landing Page: %s' %(self.title)

	def get_absolute_url(self):
	  return reverse("landings:landing-detail", kwargs={"slug":self.slug}) #f"/landings/{self.slug}/"
	
	class Meta:
	    ordering = ["-timestamp", "-updated"]

	# @property
	# def foo(self):
	# 	return self._foo

def landing_pre_save_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = unique_slug_generator(instance)

pre_save.connect(landing_pre_save_receiver, sender=LandingPage)

src/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block head_title %} {% endblock %} | My LandingHub</title>
    {% block keywords %} {% endblock %}
    {% block meta_description %} {% endblock %}
    <meta name="author" content="Sartre"/>
    <meta name="rating" content="general"/>
    <meta name="copyright" content="Copyright ©2018"/>
    <meta name="distribution" content="global"/>
    <meta name="robots" content="index, follow"/>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- Custom CSS -->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/labels-badges.css' %}" rel="stylesheet" type="text/css">
    <!-- Custom Font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:700,400,300,200|Roboto:400,500" rel="stylesheet" type="text/css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block stylesheets %}
    {% endblock %}
    {% block style %}
    {% endblock %}
    {% block chat %}
    {% endblock %}
  </head>
  <body>
    <div class="container-xl">
    {% block content %}
    {% endblock %}
    </div>
    {% block js %}
    {% endblock %}
   <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootbox.min.js' %}"></script>
  </body>
</html>

src/templates/footer.html
<hr>
<div class="footer">
	<div class="text-center">
	<h6><small><b>My LandingHub</b> <br><em>powered by <a href="mailto:platforms@geoinnovare.com">Geoinnovare Platforms</a></em></small></h6>
	<h6 class="disclaimer" ><small><small>© {% now 'Y' %} Derechos Reservados.</small></small></h6>
	</div>
	<br>
</div>

src/templates/home.html
{% extends 'base.html' %}
{% load i18n %}
{% block head_title %} Home {% endblock %}
{% block content %}
<div class="mb-5 p-5">
	<br>
	<div class="col-lg-10 offset-lg-1">
		<div class="jumbotron">
			<div class="text-center">
	        <h1>{{project_name}} | <b><small><small>My LandingHub</small></small></h1>
	        <h4><a href="{% url 'landinghub_view' %}">{% trans 'Enter' %}</a></h4> 
	        </div> 
	      </div>
	</div>
</div>
{% include 'footer.html' %}
{% endblock %}

src/templates/landinghub.html
{% extends 'base.html' %}
{% load i18n %}
{% block head_title %} LandingHub {% endblock %}
{% block content %}
<div class="mb-5 p-5">
<div class="container">
	<h2 class="text-center"><b>{% trans 'My' %} My LandingHub</b></h2>
	<h5 class="text-center">{{project_name}}</h5>
	<br>
  <div class="row">
    <div class="col col-lg-4 offset-lg-2">
   		  <div class="jumbotron">
			<div class="text-center">
	        <h3><a href="{% url 'landings:landing-list' %}">Landing Pages</h3></a>
	        </div> 
	      </div>
    </div>

    <div class="col col-lg-4">
    	<div class="jumbotron">
			<div class="text-center">
	        <h3><a href="{% url 'virtualrooms:virtualroom-list' %}">{% trans 'Virtual Rooms' %}</h3></a>
	        </div> 
	      </div>
    </div>
  </div>
</div>
</div>
{% include 'footer.html' %}
{% endblock %}

src/templates/landingpage_create-2.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block head_title %} {{title}} {% endblock %}
{% block stylesheets %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
{% endblock %}
{% block content %}
<div class="container">
{% include "navbar.html" %}
  <div class="jumbotron">
    <div class="text-center">
        <h3>{{ title_action }}</h3>
        <br>
    </div>
    <div class="row">
  		<div class="panel panel-default">

          <div class="panel-body">
            {% if form %}
            {{ form.media }}
             <form id="landing_edit_form" method="POST" class="form" role="form" action="" enctype="multipart/form-data">{% csrf_token %}
              {% crispy form  %}
              <br>
              <input type='submit' style="float:right;" value= "{% trans 'Guardar' %}&raquo;" class='btn btn-default btn-md'></input>
              <a href="{% url 'landings:landing-list' %}"  style="float:left;" class="btn btn-default btn-xs">&laquo; {% trans 'Mis Landing Page'%}</a>
            </form>
            {% endif %}
          </div>
  		  	
          <div id="spinner_tool" class="spinner text-center" style="display:none;">
            <i class="fa fa-spin fa-spinner fa-4x"></i>
            <br><br>
            <span class="label label-large label-info arrowed-in-right arrowed-in">
              Loading...
            </span>
          </div>
  		</div>
      
    </div>
  </div>
<br>
<div class="row">
{% include 'footer.html' %}
</div>
</div>
{% endblock %}
{% block js %}
<script type="text/javascript">
$(document).ready(function(){
  // if ($('#id_newsletter_popup').val() == 'NO' || $('#id_newsletter_popup').val() == 'YNL') {
  //     $("#newsletter_discount").hide();
  //   }

  //   if ($('#id_newsletter_popup').val() == 'YNLD'){
  //     $("#newsletter_discount").show();
  //   }

  //   $('#id_newsletter_popup').change(function() {
  //     var target = $('#id_newsletter_popup option:selected').val();
  //     if(target == "NO" || target == "YNL"){
  //         $("#newsletter_discount").hide();
  //         }
  //     else if (target == "YNLD"){
  //         $("#newsletter_discount").show();
  //         }
  //   });


    $('#landing_edit_form').submit(function() {
      $('#spinner_tool').show()
    });

});
</script>
{% endblock %}

src/templates/navbar.html
{% load static %}
{% load i18n %}
 <!-- Static navbar -->
<nav class="navbar navbar-expand-lg navbar-light rounded">
  <a class="navbar-brand" href="{% url 'landinghub_view' %}">{{project_name}} | <b><small><small>My LandingHub</small></small></b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#" aria-controls="" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="">
    <ul class="nav navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'landings:landing-list' %}">{% trans 'My Landing Pages' %}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'virtualrooms:virtualroom-list' %}">{% trans 'My Virtual Rooms' %}</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans 'User' %}: {{request.user}}</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href='/accounts/logout/'>{% trans "Log out" %}</a>  
        </div>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href='/accounts/login/'>{% trans "Log in" %}</a>
      </li>
      {% endif %}
    </ul>    
  </div>
</nav>

src/templates/starter-template.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Starter Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/starter-template/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.4/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="starter-template.css" rel="stylesheet">
  </head>
  <body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<main role="main" class="container">

  <div class="starter-template">
    <h1>Bootstrap starter template</h1>
    <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
  </div>

</main><!-- /.container -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.4/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="/docs/4.4/dist/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script></body>
</html>