src/landinghub/urls.py
from django.contrib import admin
#from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from webpages.views import home_view, landinghub_view

#from landings.views import landing_list_view, landing_detail_view, landing_create_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', home_view, name='home'),
    path('landinghub/', landinghub_view, name='landinghub_view'),
    path('landings/', include('landings.urls')),
    path('virtual-rooms/', include('virtualrooms.urls')),
    path('newsletter/', include('signups.urls')),
    path('moreinfo/', include('moreinfos.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/signups/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
	NewsletterSignupView,
	NewsletterSignupListView,
)

app_name = 'signups'
urlpatterns = [
    path('<int:pk>/signup/', NewsletterSignupView.as_view(), name='newsletter-signup'),
    path('<int:pk>/subscriptions/', NewsletterSignupListView.as_view(), name='newsletter-subscriptions'),
  
]

src/virtualrooms/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
	virtualroom_page,
    VirtualRoomAttendeeSignupView,
    VirtualRoomAttendeeListView,
	#VirtualRoomPageDetailView,
	VirtualRoomPageListView,
	VirtualRoomPageCreateView,
	VirtualRoomPageUpdateView,
	VirtualRoomMaterialUploadView,
	VirtualRoomPageDeleteView,
)

from .ajax import (
    delete_session_material_post,
    inactive_session_material_post,
    active_session_material_post,
)

app_name = 'virtualrooms'
urlpatterns = [
    #path('', landing_list_view, name='landing-list'),
    path('all/', VirtualRoomPageListView.as_view() , name='virtualroom-list'),
    #path('create/', landing_create_view, name='landing-create'),
    path('create/', VirtualRoomPageCreateView.as_view(), name='virtualroom-create'),
    path('<int:pk>/edit/', VirtualRoomPageUpdateView.as_view(), name='virtualroom-update'),
    path('<int:pk>/upload/material/', VirtualRoomMaterialUploadView.as_view(), name='virtualroom-materials'),
    path('<int:pk>/delete/', VirtualRoomPageDeleteView.as_view(), name='virtualroom-delete'),
    path('<slug:slug>/', virtualroom_page, name='virtualroom-detail'),
    path('<int:pk>/attendee/signup/', VirtualRoomAttendeeSignupView.as_view(), name='attendee-signup'),
    path('<int:pk>/attendees/', VirtualRoomAttendeeListView.as_view(), name='attendees-list'),
    path('active/material/', active_session_material_post, name='ajax-active-session-material'),
    path('inactive/material/', inactive_session_material_post, name='ajax-inactive-session-material'),
    path('delete/material/', delete_session_material_post, name='ajax-delete-session-material'),
]

src/virtualrooms/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime
from datetime import timedelta, date
from django import forms
from django.utils.translation import ugettext_lazy as _
from datetimewidget.widgets import DateWidget, TimeWidget, DateTimeWidget
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Field, HTML

from .models import VirtualRoomPage, SessionMaterial, AttendeeVroom

class VirtualRoomPageForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super(VirtualRoomPageForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper(self)
		self.helper.form_tag = False
		self.helper.form_id = 'virtualroompage_form'
		self.helper.layout = Layout(
			Div('name', css_class='col-md-12'),
			Div('facilitator', css_class='col-md-12'),
			HTML("<hr>"),
			Div('date', css_class='col-md-12'),
			Div('hour_from', css_class='col-md-12'),
			Div('clock', css_class='col-md-12'),
			HTML("<hr>"),
			Div('online_room_url', css_class='col-md-12'),
			Div('attendee_info', css_class='col-md-12'),
		)

	class Meta:
		model = VirtualRoomPage
		fields = [
			'name',
			'facilitator',
			'date',
			'hour_from',
			'clock',
			'online_room_url',
			'attendee_info',
		]
		date2=datetime.datetime.now().date() + datetime.timedelta(days=5*30)
		dateOptions = {
			'format': 'yyyy-mm-dd',
			'todayHighlight':True,
			'autoclose': True,
			'pickerPosition': 'bottom-left',
			'startDate': datetime.datetime.now().date().isoformat(),
			'endDate': date2.isoformat()
			}
		timeOptions = {
			'format': 'hh:ii',
			'autoclose': True,
			'minuteStep': 30,
			'pickerPosition': 'bottom-left',
			}


		widgets = {
			'date': DateWidget(options=dateOptions, usel10n=True, bootstrap_version=3),
			'hour_from': TimeWidget(options=timeOptions,  usel10n=True, bootstrap_version=3),
		}


class VirtualRoomMaterialUploaForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super(VirtualRoomMaterialUploaForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper(self)
		self.helper.form_tag = False
		self.helper.form_id = 'material_form'
		self.helper.layout = Layout(
			Div('file', css_class='col-md-12'),
			Div('file_name', css_class='col-md-12'),
			HTML("<br>"),
			Div('file_description', css_class='col-md-12'),
			Div('active', css_class='col-md-12'),
		)

	class Meta:
		model = SessionMaterial
		fields = ['file', 'file_name', 'file_description', 'active']
		widgets = {
		  'file_description': forms.Textarea(attrs={'rows':1}),
		}


class VirtualRoomAttendeeForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super(VirtualRoomAttendeeForm, self).__init__(*args, **kwargs)
		self.fields['email'].widget.attrs.update({'required': 'required'})
		self.fields['name'].label = _("Name:")

	class Meta:
		model = AttendeeVroom
		fields = ['name','email']
		widgets = {
			'email': forms.TextInput(attrs={'placeholder': 'abc@email.com'}),
		}
	
		

src/virtualrooms/views.py
from django.shortcuts import render, get_object_or_404
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.html import format_html
from django.utils.translation import ugettext_lazy as _
from mailer import send_mail, send_html_mail
from django import forms

from landinghub.utils import check_in_memory_mime

from django.views.generic import (
	CreateView,
	DetailView,
	ListView,
	UpdateView,
	DeleteView,
	FormView,
)
from django.views.generic.edit import FormMixin

from .models import VirtualRoomPage, SessionMaterial, AttendeeVroom
from .forms import VirtualRoomPageForm, VirtualRoomMaterialUploaForm, VirtualRoomAttendeeForm

#Project Vars
project_logo = settings.PROJECT_LOGO
project_name = settings.PROJECT_NAME
project_domain = settings.PROJECT_DOMAIN
project_product_desc = settings.PRODUCT_DESCRIPTION

class AjaxTemplateMixin(object):

    def dispatch(self, request, *args, **kwargs):
        if not hasattr(self, 'ajax_template_name'):
            split = self.template_name.split('.html')
            split[-1] = '_inner'
            split.append('.html')
            self.ajax_template_name = ''.join(split)
        if request.is_ajax():
            self.template_name = self.ajax_template_name
        return super(AjaxTemplateMixin, self).dispatch(request, *args, **kwargs)

#class-based views
class VirtualRoomPageCreateView(LoginRequiredMixin, CreateView):
	template_name = 'virtualrooms/virtualroompage_create.html'
	form_class = VirtualRoomPageForm

	def dispatch(self, request, *args, **kwargs):
		return super(VirtualRoomPageCreateView, self).dispatch(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(VirtualRoomPageCreateView, self).get_context_data(**kwargs)
		context['project_logo'] = project_logo
		context['project_name'] = project_name
		context['title'] = _('Create Virtual Room')
		context['title_action'] = _('Create Virtual Room Access Page')
		return context

	def form_valid(self, form):
		instance = form.save(commit=False)
		#print(check_in_memory_mime(self.request.FILES['file']))
		actual_user = User.objects.get(username=self.request.user)
		instance.owner = actual_user
		# try:
		# 	instance.file_type = str(check_in_memory_mime(self.request.FILES['file']))
		# 	if instance.file_type.find('word') != -1:
		# 		instance.file_type = 'doc'
		# 	elif instance.file_type.find('spreadsheet') != -1:
		# 		instance.file_type = 'xls'
		# 	elif instance.file_type.find('powerpoint') != -1:
		# 		instance.file_type = 'ppt'
		# 	else:
		# 		pass
		# except Exception as e:
		#     print(e)
		instance.save()
		return super(VirtualRoomPageCreateView, self).form_valid(form)

class VirtualRoomPageUpdateView(LoginRequiredMixin, UpdateView):
	model = VirtualRoomPage
	form_class = VirtualRoomPageForm
	template_name = 'virtualrooms/virtualroompage_create.html'
	queryset = VirtualRoomPage.objects.all()
	#success_url ="/"
	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		page = get_object_or_404(VirtualRoomPage, id=self.kwargs['pk'])
		if self.request.user == page.owner:
			pass
		else:
			return reverse('virtualrooms:virtualroom-list')
		return super(VirtualRoomPageUpdateView, self).dispatch(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		# Call the base implementation first to get a context
		context = super(VirtualRoomPageUpdateView, self).get_context_data(**kwargs)
		# Add in a QuerySet of all the books
		page = get_object_or_404(VirtualRoomPage, id=self.kwargs['pk'])
		context['project_logo'] = project_logo
		context['project_name'] = project_name
		context['landing'] = page
		context['title'] = _('Update Virtual Room Page')
		context['title_action'] = _('Update Virtual Room Page')
		return context

	def form_valid(self, form):
		instance = form.save(commit=False)
		#print(check_in_memory_mime(self.request.FILES['file']))
		actual_user = User.objects.get(username=self.request.user)
		instance.owner = actual_user
		# try:
		# 	instance.file_type = str(check_in_memory_mime(self.request.FILES['file']))
		# 	if instance.file_type.find('word') != -1:
		# 		instance.file_type = 'doc'
		# 	elif instance.file_type.find('spreadsheet') != -1:
		# 		instance.file_type = 'xls'
		# 	elif instance.file_type.find('powerpoint') != -1:
		# 		instance.file_type = 'ppt'
		# 	else:
		# 		pass
		# except Exception as e:
		#     print(e)
		instance.save()
		return super(VirtualRoomPageUpdateView, self).form_valid(form)

class VirtualRoomPageDeleteView(LoginRequiredMixin, DeleteView,):
	queryset = VirtualRoomPage.objects.all()

	def get_context_data(self, **kwargs):
		# Call the base implementation first to get a context
		context = super(VirtualRoomPageDeleteView, self).get_context_data(**kwargs)
		context['project_logo'] = project_logo
		context['project_name'] = project_name
		context['title'] = '%s %s' %(_('Delete'), _('Virtual Room'))
		return context

	def get_success_url(self):
		return reverse('virtualrooms:virtualroom-list')

class VirtualRoomPageListView(LoginRequiredMixin, ListView):
	#template_name = ''
	#queryset = ''

	def get_context_data(self, **kwargs):
		context = super(VirtualRoomPageListView, self).get_context_data(**kwargs)
		context['project_logo'] = project_logo
		context['project_name'] = project_name
		context['title'] = _('My Virtual Rooms')
		return context

	def get_queryset(self):
		queryset = VirtualRoomPage.objects.filter(owner=self.request.user).order_by('name')
		return queryset

def virtualroom_page(request, slug):
	context = {}
	landing = get_object_or_404(VirtualRoomPage, slug=slug)
	title = _("%s") %(landing.name)
	files = SessionMaterial.objects.filter(session=landing, active=True).order_by('-updated')
	context = {
	    "object": landing,
	    "files_list": files,
		"title": title,
			}
	return render(request, "virtualrooms/virtualroompage_detail.html", context)

class VirtualRoomMaterialUploadView(FormView):
	template_name = 'virtualrooms/virtualroom_material_edit_form.html'
	form_class = VirtualRoomMaterialUploaForm

	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		virtualroom = get_object_or_404(VirtualRoomPage, id=self.kwargs['pk'])
		if self.request.user == virtualroom.owner:
			pass
		else:
			return reverse('virtualrooms:virtualroom-list')
		return super(VirtualRoomMaterialUploadView, self).dispatch(request, *args, **kwargs)

	def get_success_url(self):
	    return reverse('virtualrooms:virtualroom-materials', kwargs={'pk': self.kwargs['pk']})

	def get_context_data(self, **kwargs):
		# Call the base implementation first to get a context
		context = super(VirtualRoomMaterialUploadView, self).get_context_data(**kwargs)
		# Add in a QuerySet of all the books
		context['title'] = _('Supporting Material')
		virtualroom = VirtualRoomPage.objects.get(id=self.kwargs['pk'])
		files = SessionMaterial.objects.filter(session=virtualroom).order_by('-updated')
		context['project_logo'] = project_logo
		context['project_name'] = project_name
		context['activity'] = virtualroom
		context['files_list'] = files
		return context

	def form_valid(self, form):
	    virtualroom = VirtualRoomPage.objects.get(id=self.kwargs['pk'])
	    instance = form.save(commit=False)
	    instance.session = virtualroom
	    instance.file_type = check_in_memory_mime(self.request.FILES['file'])
	    if not instance.file_type == 'application/pdf':
	        if instance.file_type.find('word') != -1:
	            instance.file_type = 'doc'
	        elif instance.file_type.find('spreadsheet') != -1:
	            instance.file_type = 'xls'
	        elif instance.file_type.find('powerpoint') != -1:
	            instance.file_type = 'ppt'
	        else:
	            pass
	    instance.save()
	    messages.add_message(self.request, messages.SUCCESS, _('File saved correctly.'))
	    return super(VirtualRoomMaterialUploadView, self).form_valid(form)


class VirtualRoomAttendeeSignupView(SuccessMessageMixin, AjaxTemplateMixin, CreateView):
	template_name = 'virtualrooms/virtualroom_signup_form.html'
	form_class = VirtualRoomAttendeeForm
	success_url = reverse_lazy('home')

	def dispatch(self, request, *args, **kwargs):
	    landing = get_object_or_404(VirtualRoomPage, id=self.kwargs['pk'])
	    return super(VirtualRoomAttendeeSignupView, self).dispatch(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
	    context = super(VirtualRoomAttendeeSignupView, self).get_context_data(**kwargs)
	    context['landing_id'] = self.kwargs['pk']
	    context['main_header'] = _('Please enter your name and e-mail address to identify yourself and give you access to the virtual room.')
	    #context['sub_header'] = _('By subscribing to the Newsletter we will notify you of special discounts and new product launches')
	    form_btn_text = _("Send")
	    context['btn_submit'] = form_btn_text
	    return context

	def form_valid(self, form):
		instance = form.save(commit=False)
		email = form.cleaned_data.get("email")
		fname = form.cleaned_data['name']
		if not form.cleaned_data['name']:
			fname = '-'
		instance.session = VirtualRoomPage.objects.get(id=self.kwargs['pk'])
		#phone = instance.phone_number
		instance.save()
		return HttpResponseRedirect(self.success_url)

class VirtualRoomAttendeeListView(LoginRequiredMixin, ListView):
	
	def get_context_data(self, **kwargs):
		context = super(VirtualRoomAttendeeListView, self).get_context_data(**kwargs)
		context['project_logo'] = project_logo
		context['project_name'] = project_name
		context['title'] = _('Attendees Resgistrations')

src/virtualrooms/templates/virtualrooms/virtualroom_material_edit_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block head_title %} {{title}} {% endblock %}
{% block stylesheets %}
{% endblock %}
{% block content %}
{% include "navbar.html" %}
<br>
<main role="main">
<div class="jumbotron">
  <div class="text-center">
      <h4>{{activity.name}}</h4>
      <h3><b>{% trans 'Supporting Material' %}</b></h3>
      <br>
  </div>
  {% if files_list %}
  <div class="col-md-10 offset-md-1">
   
         <br>
         <div id="spinner_tool" class="spinner" style="display:none;">
           <i class="fa fa-spin fa-spinner fa-4x"></i>
         </div>
       <div class="panel panel-default table-responsive">
         <table class="table table-condensed table-striped text-center">
              <thead>
                <tr>
                    <th style="text-align:center"><small>{% trans "Material" %}</small></th>
                    <th style="text-align:center"><small>{% trans "Name" %}</small></th>
                    <th style="text-align:center"><small>{% trans "Description" %}</small></th>
                    <th style="text-align:center"><small>{% trans "Currently available?" %}</small></th>
                    <th style="text-align:center"><small></small></th>
                </tr>
              </thead>
              <tbody>
                {% for file in files_list %}
                <tr>
                  <td><b><a href="{{file.file.url}}" target="_blank">
                   {% trans 'See' %}</a></b><br><small>({{file.file_type}})</small></td>
                  <td><small>{{file.file_name}}</small></td>
                  <td><small>{{file.file_description|default:"-"}}</small></td>
                  <td><small>{{file.active|yesno:_("Yes,No")}}</small></td>
                  <td>
                  {% if file.active == False %}

                  <small><a href="#" id="activeFileBtn{{file.id}}" class="btn btn-link btn-sm" style="text-transform: capitalize">{% trans "Active" %}</a></small>
                   {% else %}
                   <small><a href="#" id="inactiveFileBtn{{file.id}}" class="btn btn-link btn-sm" style="text-transform: capitalize">{% trans "Inactive" %}</a></small>
                  {% endif %}
                  
                   <small><a href="#" id="deleteFileBtn{{file.id}}" class="btn btn-link btn-sm" style="text-transform: capitalize">{% trans "Delete" %}</a></small>                
                 </td>
                </tr>
                {% endfor %}
              </tbody>
          </table>
         </div>
  </div>
  <hr>
  {% endif %}
  <div class="row">
	 <div class="col-md-10 offset-md-1">
  		<div class="panel panel-default">
  		  	<div class="panel-body">
            {% if form %}
            <h6 class="text-center"><em>{% trans 'Upload the file, indicate the name and description of the supporting material' %}:</em></h6>
            
  					{{ form.media }}
  						<form id="room_materials_edit_form" class="form" role='form' method='POST' action='' enctype="multipart/form-data">{% csrf_token %}
                <br>
  							{{ form | crispy }}
                <br>
  						<input type='submit' style="float:right;" value= "{% trans 'Save' %} &raquo;" class='btn btn-primary btn-lg '></input>
              <a href="{% url 'virtualrooms:virtualroom-list' %}" style="float:left;" class="btn btn-primary btn-sm">&laquo; {% trans 'My Virtual Rooms'%}</a>
  						</form>
  					{% endif %}
            <br>
          </div>
          <div id="spinner_tool" class="spinner text-center" style="display:none;">
            <i class="fa fa-spin fa-spinner fa-4x"></i>
            <br><br>
            <span class="label label-large label-info arrowed-in-right arrowed-in">
              Loading...
            </span>
          </div>
        </div>
    
    </div>
  </div>
</div>
{% include "footer.html" %}
</main>
{% endblock %}
{% block js %}
<script type="text/javascript">
document.addEventListener("DOMContentLoaded", function(){

  $('#room_materials_edit_form').submit(function() {
    $('#spinner_tool').show()
  });

  $('.alert').hide();
  setTimeout(function() {$(".alert").fadeIn();}, 800);
  setTimeout(function() {$(".alert").fadeOut();}, 2000);

 {% for file in files_list %}

 $('#activeFileBtn{{file.id}}').click(function(event){
   event.preventDefault();
   active_file_post{{file.id}}();
 });

 $('#inactiveFileBtn{{file.id}}').click(function(event){
   event.preventDefault();
   inactive_file_post{{file.id}}();
 });

  $('#deleteFileBtn{{file.id}}').click(function(event){
     event.preventDefault();
     delete_file_post{{file.id}}();
   });

function active_file_post{{file.id}}() {
  bootbox.confirm({
  title: '{% trans "Active Material?" %}',
  message: '{% trans "This material will be available for download. Confirm to validate:" %}',
  buttons: {
      cancel: {
          label: '<i class="fa fa-times"></i> {% trans "Cancel" %}',
          className: 'btn-primary btn-sm'
      },
      confirm: {
          label: '<i class="fa fa-check"></i> {% trans "Confirm" %}',
          className: 'btn-primary btn-sm'
      }
  },
  callback: function (result) {
    if (result === false) {

     } else {
       $.ajax({
           url : "{% url 'virtualrooms:ajax-active-session-material' %}",
           type : "POST",
           data : { id: {{file.id}}, csrfmiddlewaretoken: '{{ csrf_token }}' },
           beforeSend: function(){
             $('#spinner_tool').show()
                },
           complete: function(){
             $('#spinner_tool').hide();
                 },
           success : function(data) {
             if (data.status == 1){
               alert(data.result);
               location.reload();
              }
             if (data.status == 0){
               alert(data.error);
             }
           },
           error : function(xhr,errmsg,err) {
               $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                   " <a href='#' class='close'>&times;</a></div>");
           }
       });}

      }

    });
  }


function inactive_file_post{{file.id}}() {
  bootbox.confirm({
  title:  '{% trans "Inactive Material?" %}',
  message:  '{% trans "This material will not be available for download, please confirm to validate:" %}',
  buttons: {
      cancel: {
          label: '<i class="fa fa-times"></i> {% trans "Cancel" %}',
          className: 'btn-primary btn-sm'
      },
      confirm: {
          label: '<i class="fa fa-check"></i> {% trans "Confirm" %}',
          className: 'btn-primary btn-sm'
      }
  },
  callback: function (result) {
    if (result === false) {

     } else {
       $.ajax({
           url : "{% url 'virtualrooms:ajax-inactive-session-material' %}",
           type : "POST",
           data : { id: {{file.id}}, csrfmiddlewaretoken: '{{ csrf_token }}' },
           beforeSend: function(){
             $('#spinner_tool').show()
                },
           complete: function(){
             $('#spinner_tool').hide();
                 },
           success : function(data) {
             if (data.status == 1){
               alert(data.result);
               location.reload();
              }
             if (data.status == 0){
               alert(data.error);
             }
           },
           error : function(xhr,errmsg,err) {
               $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                   " <a href='#' class='close'>&times;</a></div>");
           }
       });}

      }

    });
  }


function delete_file_post{{file.id}}() {
          bootbox.confirm({
          title:  '{% trans "Delete Material?" %}',
          message: '{% trans "Confirm to permanently delete this file:" %}',
          buttons: {
              cancel: {
                  label: '<i class="fa fa-times"></i> {% trans "Cancel" %}',
                  className: 'btn-primary btn-sm'
              },
              confirm: {
                  label: '<i class="fa fa-check"></i> {% trans "Confirm" %}',
                  className: 'btn-primary btn-sm'
              }
          },
          callback: function (result) {
            if (result === false ) {

             } else {
               $.ajax({
                   url : "{% url 'virtualrooms:ajax-delete-session-material' %}",
                   type : "POST",
                   data : { id: {{file.id}}, csrfmiddlewaretoken: '{{ csrf_token }}' },
                   beforeSend: function(){
                     $('#spinner_tool').show()
                        },
                   complete: function(){
                     $('#spinner_tool').hide();
                         },
                   success : function(data) {
                     if (data.status == 1){
                      alert(data.result);
                      location.reload();

                      }
                     if (data.status == 0){
                       alert(data.error);
                     }
                   },
                   error : function(xhr,errmsg,err) {
                       $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                           " <a href='#' class='close'>&times;</a></div>");
                   }
               });}
               
             }

       });

      }


{% endfor %}
})
</script>
{% endblock js %}

src/virtualrooms/templates/virtualrooms/virtualroom_signup_form.html
{% load i18n %}
{% block head_title %} {{title}} {% endblock %}
{% block style %} {% endblock %}
{% block content %}
{% include 'virtualrooms/virtualroom_signup_form_inner.html' %}

{% endblock %}

src/virtualrooms/templates/virtualrooms/virtualroom_signup_form_inner.html
{% load crispy_forms_tags %}
{% load i18n %}
{% load tz %}
<div class="row">
	<div class="col-sm-12 col-xs-12">
		<div class="panel">
			<br>
		  	<div class="panel-body">
					<div style="text-align:center">
						<h4><b>{{main_header}}</h4></b>
						<br>
						<small>{{sub_header}}</small>
					</div>
					<br>
          {% if form %}
		{{ form.media }}
			<form class="form-horizontal" method='POST' action="{% url 'virtualrooms:attendee-signup' landing_id %}">{% csrf_token %}
					{{ form | crispy }}
					<br>
					<input type='submit' value= "{{btn_submit}} &raquo;" class='btn btn-block btn-success btn-lg' ></input>
			</form>
		{% endif %}
        </div>
    </div>
	</div>
</div>
{% block js %}
{% endblock %}

src/virtualrooms/templates/virtualrooms/virtualroompage_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block head_title %} {{title}} {% endblock %}
{% block content %}
{% include "navbar.html" %}
<br>
<main role="main">
	<div class="jumbotron">
			<div class="text-center">
	        	<h3>{% trans 'Virtual Rooms' %}:</h3> 
	        	<h4><small>
	        		<a href="{% url 'virtualrooms:virtualroom-create' %}">{% trans 'Create New' %}</a>
	        	</small></h4>
	        </div>
	  		<br>
	        <div>
			<ul class="list-group">
			{% for object in object_list %}
			  <li class="list-group-item">
			   <h4>{{object.name}}</h4>
			   <small><a href="{% url 'virtualrooms:virtualroom-detail' object.slug %}"><b>{% trans 'See Room' %}</b></a> | <a href="{% url 'virtualrooms:virtualroom-update' object.id %}"><b>{% trans 'Edit' %}</b></a> | <a href="{% url 'virtualrooms:virtualroom-delete' object.id %}"><b>{% trans 'Delete' %}</b></a> | <a href="{% url 'virtualrooms:virtualroom-materials' object.id %}">{% trans 'Supporting Material' %}</a> | <a href="{% url 'virtualrooms:attendees-list' object.id %}">{% trans 'Attendees List' %}</a></small>
			  </li>
			{% endfor %}
			</ul>
			</div>
	</div>
{% include 'footer.html' %} 
</main>
{% endblock %}